export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as Book } from './Book';
export { default as AddBook } from './AddBook';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Title } from './Title';
export { default as BookItem } from './BookItem';
export { default as BookItemSim } from './BookItemSim';
export { default as Nav } from './Nav';
export { default as CheckBook } from './CheckBook';
export { default as BookLoanList } from './BookLoanList.js';
export { default as LoginOut } from './LoginOut.js';
export { default as CenterItem } from './CenterItem.js';
export { default as UserHead } from './UserHead.js';
export { default as Category } from './Category.js';
export { default as UserItem } from './UserItem.js';
export { default as TButton } from './TButton.js';
export { default as TModalIn } from './TModalIn.js';
export { default as TModalTip } from './TModalTip.js'
export { default as BorrowRule } from './BorrowRule.js'
export { default as AddressItem } from './AddressItem.js' 
